image: python:3.7

cache:
  paths:
  - ~/.cache/pip/

stages:
  - build

Style check:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements_fast.txt
    - pip install flake8
  script:
    - flake8

Type check:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements_fast.txt
    - pip install pytype
  script:
    - pytype .

Unit tests:
  stage: build
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements_fast.txt
  script:
    - python -m main --fast
