image: python:3.7

cache:
  paths:
  - ~/.cache/pip/

stages:
#  - build
  - check

#Docker build:
#  stage: build
#  image: docker:20
#  tags:
#    - shared-fi
#  script:
#    - docker build -t regemt:latest
#    - docker push regemt:latest

Style check:
  stage: check
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements_fast.txt
    - pip install flake8
  script:
    - flake8

Type check:
  stage: check
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements_fast.txt
    - pip install pytype
  script:
    - pytype .

Unit tests:
  stage: check
  tags:
    - shared-fi
  before_script:
    - python -V
    - pip install -U pip
    - pip install -r requirements_fast.txt
  script:
    - python -m main --fast
  artifacts:
    paths:
      - heatmap-*.png
      - metric-*.png
    expire_in: 1 week
