name: Test and publish
on:
  push:
    branches: ['docker-build']
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.7', '3.8', '3.9']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip
          pip install -r requirements_fast.txt
          pip install flake8
      - name: Style check
        run: flake8
  type-check:
    name: Type check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.7', '3.8', '3.9']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip
          pip install -r requirements_fast.txt
          pip install pytype
      - name: Type check
        run: pytype .
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: ['3.7', '3.8', '3.9']
    container:
      image: python:${{ matrix.python }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install requirements
        run: |
          set -ex
          python -V
          pip install -U pip
          pip install -r requirements_fast.txt
      - name: Unit tests
        run: python -m main --fast
      - name: Upload metric correlations as heatmaps
        uses: actions/upload-artifact@v2
        with:
          name: heatmaps-${{ matrix.python }}
          path: submit_dir/heatmap-*.png
      - name: Upload visualizations of regression metrics
        uses: actions/upload-artifact@v2
        with:
          name: metrics-${{ matrix.python }}
          path: submit_dir/metric-*.png
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: ['style-check', 'type-check', 'unit-tests']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t miratmu/regemt:latest .
      - name: Authenticate registry
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Publish image
        run: |
          docker push miratmu/regemt:latest
